# Matrix Multiplication and Linear Regression

This notebook applies matrix multiplication and a simple linear regression equation to real-world examples.

In [4]:
# 1. Multiply two 2x2 Instagram engagement matrices
import numpy as np

# Rows represent Instagram posts; columns represent two days.
likes_matrix = np.array([
    [120, 150],
    [200, 180]
])
comments_matrix = np.array([
    [10, 12],
    [15, 20]
])
result_matrix = likes_matrix @ comments_matrix

print("Likes matrix (posts x days):")
print(likes_matrix)
print("Comments matrix (posts x days):")
print(comments_matrix)
print("Result of matrix multiplication:")
print(result_matrix)
print("Each result entry is the dot product of a row from the likes matrix and a column from the comments matrix.")

Likes matrix (posts x days):
[[120 150]
 [200 180]]
Comments matrix (posts x days):
[[10 12]
 [15 20]]
Result of matrix multiplication:
[[3450 4440]
 [4700 6000]]
Each result entry is the dot product of a row from the likes matrix and a column from the comments matrix.


In [2]:
# 2. Predict an output using a linear regression equation

def linear_regression_predict(x, m, c):
    """Return y = mx + c."""
    return m * x + c


x = 5
m = 4
c = 10
predicted_y = linear_regression_predict(x, m, c)
print(f"For x={x}, m={m}, and c={c}, predicted y={predicted_y}")

For x=5, m=4, and c=10, predicted y=30


In [3]:
# 3. Predict Zomato delivery times from distances

def linear_regression_predict(x, m, c):
    return m * x + c


distances_km = [2, 5, 8]
slope = 4
intercept = 10
predicted_times = [
    linear_regression_predict(distance, slope, intercept)
    for distance in distances_km
]

for distance, time in zip(distances_km, predicted_times):
    print(f"Distance: {distance} km -> Predicted delivery time: {time} minutes")

Distance: 2 km -> Predicted delivery time: 18 minutes
Distance: 5 km -> Predicted delivery time: 30 minutes
Distance: 8 km -> Predicted delivery time: 42 minutes


## 4. Slope and Intercept in Flipkart Price Prediction

**Slope:** The slope shows how much the predicted product price changes when the product rating increases by one point. A positive slope means higher-rated products are predicted to cost more, while a negative slope means the predicted price decreases as the rating increases.

**Intercept:** The intercept is the predicted product price when the rating is zero. It provides the starting point of the regression line, although a rating of zero may not be realistic in the actual Flipkart data.

## 5. Matrix Multiplication in Spotify Recommendations

**Prompt:** How does matrix multiplication help in training a machine learning model like Spotify's song recommendation system?

**Answer:** Matrix multiplication combines user preferences with song features to calculate how well each user may like each song. During training, the model adjusts its user and song matrices so that predicted ratings become closer to actual listening behaviour. The resulting scores help Spotify rank songs and recommend the most relevant tracks to each listener.